version: "3"

services:

  tipapp-web:
    image: "tipapp/web"
    build:
      context: ./web
    ports:
      - "8000:80"
    depends_on:
      - tipapp-service

  tipapp-service:
    image: "tipapp/service"
    build:
      context: ./service
    depends_on:
      - tipapp-database
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  
  tipapp-database:
    image: "tipapp/database"
    build:
      context: ./database
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  tipapp-wordpress:
    image: "tipapp/wordpress"
    build:
      context: ./wordpress
    restart: always
    ports:
      - 8100:80
    environment:
      WORDPRESS_DB_HOST: tipapp-mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password

  tipapp-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

