name: Run Service API Python Unit Tests
on: [push]

jobs:
  build:
    name: Service API Unit Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Python Pytest Github Action
          uses: fylein/python-pytest-github-action@v2
          with:
            args: cd service && pip3 install -r requirements.txt -r tests/requirements.txt && pytest --cov=app tests
