name: Web Application Deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run Production Configuration Build
        run: |
          cd web
          npm ci
          npm run build:production

      - name: Copy Files to Droplet
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets. DIGITALOCEAN_HOST_WEB }}
            username: ${{ secrets. DIGITALOCEAN_USERNAME }}
            key: ${{ secrets. DIGITALOCEAN_KEY }}                        
            source: "web/dist/tipapp"
            target: "/var/www/html/tipnorthshore.net/tipapp"
            strip_components: 3
            rm: true